name: milliden_app
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"
  

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  carousel_slider: ^5.1.1
  flutter_social_button: ^1.1.6+1
  font_awesome_flutter: ^10.7.0
  url_launcher: ^6.0.0
  http: ^1.5.0
  flutter_map: ^8.2.1
  dwds: ^25.1.0
  latlong2: 0.9.1
  webview_flutter: ^4.4.2
  
  


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - lib/assets/images/Logo.jpeg
    - lib/assets/images/o1.jpeg
    - lib/assets/images/l6.jpeg
    - lib/assets/images/r1.jpeg
    - lib/assets/images/lawn1.jpeg
    - lib/assets/images/bake.png
    - lib/assets/images/g7.jpeg
    - lib/assets/images/r1.png
    - lib/assets/images/i3.png
    - lib/assets/images/i2.png
    - lib/assets/images/i1.png


      
